name: sync_event
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0
  shimmer: ^3.0.0

  # Clean Architecture
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  injectable: ^2.4.4

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.3.7

  # Authentication
  google_sign_in: ^6.3.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Storage
  shared_preferences: ^2.3.4

  # Navigation
  go_router: ^14.6.2

  # Utilities
  file_picker: ^8.1.4
  intl: ^0.20.2

  # Maps and Location
  google_maps_flutter: ^2.10.0
  location: ^7.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  http: ^1.5.0
  flutter_typeahead: ^5.2.0
  flutter_google_places_sdk: any
  permission_handler: ^11.3.1
  image_picker: ^1.2.0
  url_launcher: ^6.3.2
  image: ^4.5.4
  flutter_cache_manager: ^3.4.1
  collection: ^1.19.1
  open_file: ^3.5.10
  razorpay_flutter: ^1.4.0
  mailer: ^6.5.0
  pdf: ^3.11.1
  printing: ^5.13.4
  rxdart: ^0.28.0
  riverpod_annotation: ^2.6.1
  table_calendar: ^3.1.3
  syncfusion_flutter_calendar: ^29.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png