name: sync_event
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: any
  flutter_svg: any
  flutter_screenutil: any
  font_awesome_flutter: any
  google_fonts: any
  smooth_page_indicator: any
  shimmer: any

  # Clean Architecture
  dartz: any
  equatable: any
  get_it: any
  injectable: any

  # Firebase
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any

  # Authentication
  google_sign_in: ^6.3.0

  # State Management
  flutter_riverpod: any

  # Storage
  shared_preferences: any

  # Navigation
  go_router: any

  # Utilities
  file_picker: any
  intl: any

  # Maps and Location
  google_maps_flutter: any
  location: any
  geolocator: any
  geocoding: any
  http: any
  flutter_typeahead: any
  flutter_google_places_sdk: any
  permission_handler: any
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  injectable_generator: any
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png