// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0xLi8vX--E0qGpcEgm1jhmG3hbkI2P9s',
    appId: '1:329366449067:web:512541f006fa604edf80ee',
    messagingSenderId: '329366449067',
    projectId: 'sync-bded7',
    authDomain: 'sync-bded7.firebaseapp.com',
    storageBucket: 'sync-bded7.firebasestorage.app',
    measurementId: 'G-BMW09S7SVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMl7PvyH-piO_p-ly_w111BXtD9fUyNg',
    appId: '1:329366449067:android:6b020e606e70731edf80ee',
    messagingSenderId: '329366449067',
    projectId: 'sync-bded7',
    storageBucket: 'sync-bded7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5uIXyCqobemk_GcKYpX10gJjrbPjLnYg',
    appId: '1:329366449067:ios:3e4d29ee73389185df80ee',
    messagingSenderId: '329366449067',
    projectId: 'sync-bded7',
    storageBucket: 'sync-bded7.firebasestorage.app',
    androidClientId:
        '329366449067-ek1cl8pmiaave8niat55o9a0md8pc49s.apps.googleusercontent.com',
    iosClientId:
        '329366449067-m0d7a8dd4ghv27ndqs2aqsuakjlr2hd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5uIXyCqobemk_GcKYpX10gJjrbPjLnYg',
    appId: '1:329366449067:ios:3e4d29ee73389185df80ee',
    messagingSenderId: '329366449067',
    projectId: 'sync-bded7',
    storageBucket: 'sync-bded7.firebasestorage.app',
    androidClientId:
        '329366449067-ek1cl8pmiaave8niat55o9a0md8pc49s.apps.googleusercontent.com',
    iosClientId:
        '329366449067-m0d7a8dd4ghv27ndqs2aqsuakjlr2hd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.syncEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0xLi8vX--E0qGpcEgm1jhmG3hbkI2P9s',
    appId: '1:329366449067:web:512e7f45b2420e8edf80ee',
    messagingSenderId: '329366449067',
    projectId: 'sync-bded7',
    authDomain: 'sync-bded7.firebaseapp.com',
    storageBucket: 'sync-bded7.firebasestorage.app',
    measurementId: 'G-VD7XPHWQQK',
  );
}
